# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    allowed_methods_listener: true
    routing_loader: false
    exception:
        enabled: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, priorities: [json] }
            - { path: ^/, prefer_extension: true, priorities: [html] }
    view:
        view_response_listener: 'force'
        formats:
            json: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    body_listener: true
    #body_converter:
    #    enabled: true
